# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 8, 24, 23, 20, 19, 80670, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
